### ISSUE TITLE
Need help with jdbc:postgres connection settings 

### ISSUE THREAD

**Issue by MaximVetlugin** [odpi/egeria-connector-xtdb#246]
Good day!

I tried to set up Egeria local-repository connection to Postgres (as doc-store).

With Egeria 3.0 and egeria-connector-xtdb 3.0 I have had success. Table created, data stored.
Except one - it connects only to localhost because error with creating jdbc url (it doubles first part of url).

Then I start Egeria 3.2 and egeria-connector-xtdb 3.1.
Now I can not connect to any Postgres host.

The error in log is:

```
Thu Oct 07 23:35:35 MSK 2021 platform-local Exception OMRS-CRUX-REPOSITORY-0008 Supplementary information: log record id a0a2e687-bcc7-4dbb-9c3b-c943c8ce8993 crux.IllegalArgumentException returned message of Error parsing opts for [:crux.jdbc/connection-pool] and stacktrace of

..... 

Caused by: crux.IllegalArgumentException: Arg :db-spec = {host=localhost, dbname=egeria, user=egeria, password=egeria} invalid: {"host" "localhost", "dbname" "egeria", "user" "egeria", "password" "egeria"} - failed: map?


```
The used config is:

            "localRepositoryConfig": {
                "class": "LocalRepositoryConfig",
                "metadataCollectionId": "2b3dd99f-2057-4cd5-8175-8397f8a136ea",
                "localRepositoryMode": "PLUGIN_REPOSITORY",
                "localRepositoryLocalConnection": {
                    "class": "Connection",
                    "headerVersion": 0,
                    "connectorType": {
                        "class": "ConnectorType",
                        "headerVersion": 0,
                        "connectorProviderClassName": "org.odpi.egeria.connectors.juxt.crux.repositoryconnector.CruxOMRSRepositoryConnectorProvider"
                    },
                    "configurationProperties": {
                        "cruxConfig": {
                            "crux.jdbc/connection-pool": {
                                "dialect": {
                                    "crux/module": "crux.jdbc.psql/->dialect"
                                },
                                "db-spec": {
                                    "host": "localhost",
                                    "dbname": "egeria",
                                    "user": "egeria",
                                    "password": "egeria"
                                },
                                "poll-sleep-duration": "PT1S"
                            },
                            "crux/document-store": {
                                "crux/module": "crux.jdbc/->document-store",
                                "connection-pool": "crux.jdbc/connection-pool"
                            },
                            "crux/tx-log": {
                                "crux/module": "crux.kafka/->tx-log",
                                "bootstrap-servers": "localhost:9092",
                                "tx-topic-opts": {
                                    "topic-name": "xtdb-transaction-log-local"
                                }
                            },
                            "crux/index-store": {
                                "kv-store": {
                                    "crux/module": "crux.rocksdb/->kv-store",
                                    "db-dir": "data/servers/platform-local/rdb-index"
                                }
                            },
                            "crux.lucene/lucene-store": {
                                "db-dir": "data/servers/platform-local/lucene"
                            }
                        }
                    }
                },
                "eventsToSaveRule": "ALL",
                "eventsToSendRule": "ALL"
            }

Please, help me with this problem.
Thank you.

**Comment by cmgrote** [comment]
Hmm, that's odd...  There are some additional pieces you need to add to the Lucene config when using this EDN structure:

```clojure
{:xtdb.lucene/lucene-store {
    :db-dir "data/servers/xtdb/lucene"
    :indexer {:xtdb/module xtdb.lucene.egeria/->egeria-indexer}
    :analyzer {:xtdb/module xtdb.lucene.egeria/->ci-analyzer}}
```

Are you including all of that already?  (Prior to the name change to `xtdb` these were probably `:crux.lucene/lucene-store`, etc.)

Or perhaps there was a bug in the 3.1 release which meant something wasn't being picked up the way we'd expect...  Any chance you could re-test with the latest 3.2-SNAPSHOT version (with all the `xtdb` name changes) and see if it still doesn't work there?

**Comment by cmgrote** [comment]
Definitely strange...  would you mind pasting your config here to the issue so I can try to reproduce?  (Of course first remove any credential details from the JDBC portion: feel free to just replace username, password and host name with "xxxxx"!)

**Comment by MaximVetlugin** [comment]
That is my config for local-repository I'm sending from Postmat.

`{
    "class": "Connection",
    "connectorType": {
      "class": "ConnectorType",
      "connectorProviderClassName": "org.odpi.egeria.connectors.juxt.xtdb.repositoryconnector.XtdbOMRSRepositoryConnectorProvider"
    },
    "configurationProperties": {
      "xtdbConfigEDN": "{:xtdb/index-store {:kv-store {:xtdb/module xtdb.rocksdb/->kv-store :db-dir \"data/servers/{{server}}/rdb-index\"}} :xtdb/document-store {:xtdb/module xtdb.jdbc/->document-store :connection-pool {:dialect {:xtdb/module xtdb.jdbc.psql/->dialect} :db-spec {:jdbcUrl \"jdbc:postgresql://{{PostgreSQL}}/{{PostgreSQLDBName}}?user={{PostgreSQLLogin}}&password={{PostgreSQLPassword}}\"}}}} :xtdb/tx-log {:xtdb/module xtdb.kafka/->tx-log {:bootstrap-servers {{kafkaep}} :tx-topic-opts {:topic-name \"{{tx-topic-name}}\"}}} :xtdb.lucene/lucene-store {:db-dir \"data/servers/{{server}}/lucene\" :indexer {:xtdb/module xtdb.lucene.egeria/->egeria-indexer} :analyzer {:xtdb/module xtdb.lucene.egeria/->ci-analyzer}}}"
    }
}`

That is from file "xtdb3022697917596517591.edn"

`{:xtdb/index-store {:kv-store {:xtdb/module xtdb.rocksdb/->kv-store :db-dir "data/servers/paukd-platform-local/rdb-index"}} :xtdb/document-store {:xtdb/module xtdb.jdbc/->document-store :connection-pool {:dialect {:xtdb/module xtdb.jdbc.psql/->dialect} :db-spec {:jdbcUrl "jdbc:postgresql://localhost/paukd-platform-local?user=login&password=password"}}}} :xtdb/tx-log {:xtdb/module xtdb.kafka/->tx-log {:bootstrap-servers localhost:9092 :tx-topic-opts {:topic-name "xtdb-transaction-log-local"}}} :xtdb.lucene/lucene-store {:db-dir "data/servers/paukd-platform-local/lucene" :indexer {:xtdb/module xtdb.lucene.egeria/->egeria-indexer} :analyzer {:xtdb/module xtdb.lucene.egeria/->ci-analyzer}}}`

**Comment by cmgrote** [comment]
Ok, I can reproduce the problem at least -- now I just need to figure out what's going on to fix it 🤔
