### ISSUE TITLE
New TypeDef not persistent

### ISSUE THREAD

**Issue by Inventoroz** [odpi/egeria-connector-xtdb#256]
If you create your own TypeDef, then after restarting the Egeria, all these TypeDefs disappear
I suppose this is due to the fact that TypeDefs are cached and not made constant

https://github.com/odpi/egeria-connector-xtdb/blob/5c4a10edf3c21262489c7d471904bc43324e93e0/connector/src/main/java/org/odpi/egeria/connectors/juxt/xtdb/repositoryconnector/XtdbOMRSMetadataCollection.java#L80

Will their permanent storage be realized?

**Comment by mandy-chessell** [comment]
There are descriptions and examples in the open-metadata-resources/open-metadata-archives module. https://github.com/odpi/egeria/tree/master/open-metadata-resources/open-metadata-archives

**Comment by Inventoroz** [comment]
@cmgrote, @mandy-chessell , thank you, we tried this option. It turned out to be what we needed.
