### ISSUE TITLE
CTS failing with Egeria 3.6

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-connector-xtdb#319]
Using the latest connector, I am seeing some tests fail:
```
        "testCaseCount": 5703,
        "testFailedCount": 27,
        "testPassCount": 5676,
```
For example:
```
                        "conformanceException": {
                            "errorMessage": "CTS test repository-entity-property-search caught exception RepositoryErrorException from method findEntitiesByProperty whilst trying to find entities of type GovernanceEngine.  Exception message was : OMRS-REPOSITORY-400-062 An unexpected xtdb.IllegalArgumentException exception was caught by findEntitiesByProperty; error message was Clause refers to unknown variable: sv_name [[:pred {:pred {:pred-fn wildcard-text-search-cs, :args [\"name.1\"]}, :return [:relation [[e v name _]]]}] [:pred {:pred {:pred-fn #'clojure.core/str, :args [name]}, :return [:scalar sv_name]}] [:pred {:pred {:pred-fn #'clojure.string/ends-with?, :args [sv_name \".name.value\"]}}]].  Method was invoked with parameters: asOfTime : null, entityTypeGUID : 3fa23d4a-aceb-422f-9301-04ed474c6f74, fromEntityElement : 0, limitResultsByClassification : null, limitResultsByStatus : null, matchCriteria : None, matchProperties : InstanceProperties{propertyNames=java.util.HashMap$KeyIterator@5e82deee, propertyCount=1, instanceProperties={name=PrimitivePropertyValue{primitiveValue=\\Qname.1\\E, primitiveDefCategory=PrimitiveDefCategory{code=11, name='string', javaClassName='java.lang.String', guid='b34a64b9-554a-42b1-8f8a-7d5c2339f9c4'}, instancePropertyCategory=InstancePropertyCategory{typeCode=1, typeName='Primitive', typeDescription='A primitive type.'}, typeGUID='null', typeName='null'}}}, pageSize : 5, sequencingOrder : null, sequencingProperty : null",
                            "exceptionClassName": "java.lang.Exception"
                        },
```

Will post the full log files shortly

**Comment by planetf1** [comment]
The log files can be found at https://github.com/planetf1/files/tree/main/bugs/xtdb-319

**Comment by planetf1** [comment]
I will rerun with the snapshot version of the connector as per the comment added in referenced issue _I think most of the failures you ran into with the XT connector are from the last release -- there was a bug that's been fixed but is only currently in the SNAPSHOT builds_

**Comment by planetf1** [comment]
@cmgrote - do you have the download string you use for snapshots. 3.6-SNAPSHOT is on nexus, but I've not quite got the right URL ie
`wget "http://repository.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.odpi.egeria&a=egeria-connector-xtdb&v=3.6-SNAPSHOT&c=jar-with-dependencies"` is not working
though
`wget http://repository.sonatype.org/service/local/artifact/maven/redirect\?r\=central-proxy\&g\=org.odpi.egeria\&a\=egeria-connector-xtdb\&v\=LATEST\&c\=jar-with-dependencies`
is fine. 

I may have the repo 'snapshots' wrong? From nexus, the central repo is 'central' - and so I can't see where the mapping central->central-proxy comes from. I therefore may be missing the same link with snapshots?

**Comment by planetf1** [comment]
This seems to work
`http://oss.sonatype.org/service/local/artifact/maven/redirect\?r\=snapshots\&g\=org.odpi.egeria\&a\=egeria-connector-xtdb\&v\=3.6-SNAPSHOT\&c\=jar-with-dependencies`

**Comment by planetf1** [comment]
Tested with the latest 3.6 snapshot.

Test output added to same directory (under 'snapshot')
```
        "testFailedCount": 4,
```
This includes the same assertion failure (albeit with type long) that we see with the 3.6 CTS

**Comment by cmgrote** [comment]
No errors observed on 3.6 release with latest snapshot -- closing.
