### ISSUE TITLE
Receiving Error OMRS-XTDB-REPOSITORY-0022 during operation

### ISSUE THREAD

**Issue by dwolfson** [odpi/egeria-connector-xtdb#472]
Hi,

Running the some of the lab notebooks with XTDB over Postgres (both txn and doc) and noticed that I am getting lots of errors of the form:

egeria Tue Apr 11 11:31:20 GMT 2023 cocoMDS1 Error OMRS-XTDB-REPOSITORY-0022 The requested ClassificationOrigin enumeration with ordinal or symbolic name null does not exist.                                                                    │
│ egeria Tue Apr 11 11:31:20 GMT 2023 cocoMDS1 Error OMRS-XTDB-REPOSITORY-0022 The requested ClassificationOrigin enumeration with ordinal or symbolic name null does not exist.                                                                    │
│ egeria Tue Apr 11 11:31:20 GMT 2023 cocoMDS1 Error OMRS-XTDB-REPOSITORY-0022 The requested ClassificationOrigin enumeration with ordinal or symbolic name null does not exist.

Is ClassificationOrigin not getting set? Other thoughts? This does not appear as an error to the client..

**Comment by dwolfson** [comment]
I also see the message:
Information OMRS-XTDB-REPOSITORY-0026 Cannot sort by property By property value (Ascending) on types: [ControlledGlossaryTerm, GlossaryTerm].

When I do a search for a glossary term?

**Comment by dwolfson** [comment]
Current hypothesis is that this may have been due to an old XTDB library being loaded. It seems to be working properly - when I made sure that the latest xtdb library was being sourced. Might be nice if we printed out library versions when we load them (maybe we do).

**Comment by planetf1** [comment]
I hope to implement the above -- if so, it's a good time to revisit what could be logged.
